---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-jenkins-prod
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mickaelkremer@gmail.com
    privateKeySecretRef:
      name: letsencrypt-jenkins-prod
    solvers:
    - http01:
        ingress:
          class: traefik
---