---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: default
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-jenkins-prod
spec:
  ingressClassName: traefik
  # tls:
  #   - secretName: jenkins-secret
  #     hosts:
  #       - jenkins.maikimike.cloudns.be
  rules:
    - host: exam.jenkins.dev
      http:
        paths:
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: nginx-svc
          #       port:
          #         number: 80
          - path: /api/v1/movies
            pathType: Prefix
            backend:
              service:
                name: movie
                port:
                  number: 80
          - path: /api/v1/casts
            pathType: Prefix
            backend:
              service:
                name: cast
                port:
                  number: 80
---