---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
  namespace: default
spec:
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z movie-db 5432; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']   
      containers:
      - name: movie
        image: mikalander77/jenkins_exam_movie:latest
        # command: ["uvicorn", "app.main:app", "--reload",  "--host", "0.0.0.0", "--port", "8000"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: movie-db-configmap
                key: postgres-dbname
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: movie-db-secret
                key: postgres-root-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: movie-db-secret
                key: postgres-root-password
          - name: DATABASE_URI
            value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@movie-db/$(POSTGRES_DB)"
          - name: CAST_SERVICE_HOST_URL
            value: "http://cast.default.svc.cluster.local:80/api/v1/casts/"
---
apiVersion: v1
kind: Service
metadata:
  name: movie
  namespace: default
spec:
  type: NodePort
  selector:
    app: movie
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30100
---
